add on click listener
bccfilkom/gridmenu pull request #11
Opened 2019-11-28 11:46 UTC by zakwandhiya

i try to add on click listener interface

2019-11-28 15:49 UTC, adityapp requested changes

2019-11-28 15:49 UTC, adityapp commented on gridmenuview/src/main/java/com/bcc/gridmenuview/GridMenuOnClickListener.java
> +    void ontClick (int position);
typo name of the function

2019-11-29 11:32 UTC, gifff requested changes

2019-11-29 11:32 UTC, gifff commented on gridmenuview/src/main/java/com/bcc/gridmenuview/GridMenuAdapter.java
> +                gridMenuOnClickListener.ontClick(holder.getAdapterPosition());
Please add null-safety check against the listener

2019-11-29 11:32 UTC, gifff commented on gridmenuview/src/main/java/com/bcc/gridmenuview/GridMenuOnClickListener.java
> +public interface GridMenuOnClickListener {
I guess `OnItemClickListener` is more suitable for the name

2019-12-03 07:31 UTC, gifff approved these changes

2019-12-03 08:43 UTC, zainfikrih approved these changes
👍🏼

2019-12-03 13:31 UTC, adityapp requested changes

2019-12-03 13:31 UTC, adityapp commented on app/src/main/java/com/bcc/gridmenu/MainActivity.java
> +                Log.i("===== ", "onClick: " + position);
delete this log

2019-12-03 14:14 UTC, adityapp approved these changes

2019-12-03 14:16 UTC, merged