Refactor project
bccfilkom/gridmenu pull request #7
Opened 2019-11-21 16:29 UTC by zainfikrih

- rename library
- rename package app
- rename package module

2019-11-21 18:20 UTC, adityapp commented on app/build.gradle
> +        applicationId "com.filkom.bcc.gridmenu"
change to "com.bcc.gridmenu"

2019-11-21 18:31 UTC, adityapp requested changes
please change package name to "com.bcc.gridmenu"

2019-11-22 03:26 UTC, adityapp approved these changes

2019-11-22 03:59 UTC, gifff commented on app/build.gradle
> -    implementation project(path: ':squaremenu')
@adityapp is it better to use `gridmenu` for the library name and change the sample app name to something else?

2019-11-22 04:00 UTC, gifff commented on app/build.gradle
> +    implementation project(path: ':gridmenulibrary')
@adityapp is it better to use `gridmenu` for the library name and change the sample app name to something else?

2019-11-22 13:53 UTC, adityapp approved these changes

2019-11-23 03:44 UTC, gifff approved these changes

2019-11-23 03:51 UTC, merged